export default defineAppConfig({
  ui: {
    // All ramps are generated by scripts/gen-palette.mjs (single source of truth).
    // Semantic hues are pinned away from the brand so `success` never drowns
    // against the teal-family surfaces.
    colors: {
      primary: 'brand',
      neutral: 'slate',
      success: 'success',
      error: 'error',
      warning: 'warning',
      info: 'info',
    },
    // Dark inputs read as near-black wells against the surfaces with the default
    // bg-default fill; a translucent surface-800 fill keeps them in the family and
    // slightly raised from card/page backgrounds.
    input: {
      slots: {
        base: 'dark:bg-surface-800/40',
      },
    },
    textarea: {
      slots: {
        base: 'dark:bg-surface-800/40',
      },
    },
    select: {
      slots: {
        base: 'dark:bg-surface-800/40',
      },
    },
    toaster: {
      slots: {
        // Lift bottom-anchored toasts above the Android gesture bar (env() is 0
        // on web/desktop; margin-bottom is inert for top-anchored positions).
        viewport: 'mb-[env(safe-area-inset-bottom,0px)]',
      },
    },
  },
});
