#!/usr/bin/env node
// Adyton color-system generator — the single entry point for a rebrand.
//
//   node scripts/gen-palette.mjs                         # regenerate from defaults
//   node scripts/gen-palette.mjs --light '#fff8c9' --dark '#002b3f'
//   node scripts/gen-palette.mjs --check                 # audit only, no write
//
// It builds the full palette from the two brand anchors (a light one + a dark
// one), rewrites the GENERATED
// block in apps/web/app/assets/css/main.css, prints the WCAG table, and exits
// non-zero if any load-bearing pair fails AA — so a rebrand can't silently ship
// an inaccessible theme.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildPalette, auditAA, DEFAULT_ANCHORS, DEFAULT_SEMANTIC_HUES } from './lib/palette.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CSS_PATH = resolve(__dirname, '../apps/web/app/assets/css/main.css');
const START =
  '/* === ADYTON PALETTE — GENERATED by scripts/gen-palette.mjs. DO NOT EDIT BY HAND. === */';
const END = '/* === END ADYTON PALETTE === */';
const STOPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

function parseArgs(argv) {
  const opts = { anchors: { ...DEFAULT_ANCHORS }, check: false, chromaScale: 1 };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--light') opts.anchors.light = argv[++i];
    else if (a === '--dark') opts.anchors.dark = argv[++i];
    else if (a === '--chroma-scale') opts.chromaScale = Number(argv[++i]);
  }
  return opts;
}

function rampLines(prefix, ramp) {
  return STOPS.map((s) => `  --color-${prefix}-${s}: ${ramp[s]};`).join('\n');
}

function tokenLines(tokens, indent = '  ') {
  return Object.entries(tokens)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join('\n');
}

function buildBlock(p, opts) {
  const semanticRamps = Object.keys(p.semantic)
    .map((name) => rampLines(name, p.semantic[name]))
    .join('\n');
  return `${START}
/* Source anchors: light ${opts.anchors.light} · dark ${opts.anchors.dark}
   Brand hue ${p.brandHue.toFixed(1)}° · surface hue ${p.neutralHue.toFixed(1)}° · chroma scale ${opts.chromaScale}.
   To rebrand: change the anchors and re-run \`node scripts/gen-palette.mjs\`.
   Light + dark themes and all utility ramps below are DERIVED — never hand-edit. */
@theme static {
  /* Brand ramp — accents / primary only. */
${rampLines('brand', p.brand)}

  /* Surface ramp — near-neutral graphite with a faint hue whisper. Drives all
     surfaces so dark mode is no longer a wall of saturated brand. */
${rampLines('surface', p.surface)}

  /* Semantic ramps — hues pinned away from the brand so success never drowns. */
${semanticRamps}
}

/* Layer 3 — role mapping. Light + dark mirrored on the lightness axis. */
:root {
${tokenLines(p.light)}
}
.dark {
${tokenLines(p.dark)}
}
${END}`;
}

function printAudit(audit, p) {
  console.info(
    `\nBrand hue ${p.brandHue.toFixed(1)}°  ·  surface hue ${p.neutralHue.toFixed(1)}°\n`,
  );
  for (const r of audit.rows) {
    const tag = r.pass ? 'PASS' : 'FAIL';
    console.info(
      `  ${tag}  ${r.ratio.toFixed(2).padStart(6)}:1  (need ${r.threshold})  ${r.label}`,
    );
  }
  console.info(`\n  OVERALL: ${audit.pass ? 'PASS' : 'FAIL'}\n`);
}

async function main() {
  const opts = parseArgs(process.argv);
  const palette = buildPalette({
    anchors: opts.anchors,
    semanticHues: DEFAULT_SEMANTIC_HUES,
    chromaScale: opts.chromaScale,
  });
  const audit = auditAA(palette);
  printAudit(audit, palette);

  if (!audit.pass) {
    console.error('Refusing to write: palette fails WCAG AA. Adjust anchors/chroma and retry.');
    process.exit(1);
  }
  if (opts.check) {
    console.info('--check: audit only, no file written.');
    return;
  }

  const css = await readFile(CSS_PATH, 'utf8');
  const block = buildBlock(palette, opts);
  const startIdx = css.indexOf(START);
  const endIdx = css.indexOf(END);
  let next;
  if (startIdx !== -1 && endIdx !== -1) {
    next = css.slice(0, startIdx) + block + css.slice(endIdx + END.length);
  } else {
    // First run: insert after the @import lines.
    const afterImports = css.lastIndexOf('@import');
    const nl = css.indexOf('\n', afterImports);
    next = css.slice(0, nl + 1) + '\n' + block + '\n' + css.slice(nl + 1);
  }
  await writeFile(CSS_PATH, next, 'utf8');
  console.info(`Wrote palette → ${CSS_PATH}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
